### ISSUE TITLE
text too close to borders on tablet/mobile size 

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-careers-search#3]
same issue on this template so i'm reporting here as well 
![margins](https://cloud.githubusercontent.com/assets/19909772/18005061/ec1962c0-6b97-11e6-8c0c-372ca4895e88.PNG)

**Comment by matthewmorek** [comment]
@jrah Is this still a problem after some of the updates I made more recently?

**Comment by danielapizzurro** [comment]
@matthewmorek @jrah as far as I see we're still having some of these issues at **sm** and **md** media queries

**Comment by jrah** [comment]
@matthewmorek  @danielapizzurro Yes, I can confirm this not working. The `max-width` needs to be reduced in context to accommodate for the smaller breakpoints, e.g. 

`max-width` = `800px` at `768px`.
