### ISSUE TITLE
On IE 11: design issues on drop down fields 

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-careers-search#4]
![ie 11](https://cloud.githubusercontent.com/assets/19909772/18098477/a9838582-6ee2-11e6-9e1a-61fb4fbdc1de.PNG)

**Comment by matthewmorek** [comment]
@jrah Could you please take care of this within WFP UI, by hiding a `select::-ms-expand` pseudo-element? Here's the reference: http://stackoverflow.com/a/18878556/221228.
