### ISSUE TITLE
Empty dropdown on Firefox 48 + Win 7

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-careers-search#7]
![no text](https://cloud.githubusercontent.com/assets/19909772/18475363/6f5f3b28-79c6-11e6-84da-dcb476cc793b.PNG)

**Comment by matthewmorek** [comment]
@danielapizzurro Can you replicate the issue on the properly implemented Drupal 8 instance of that page? Values will be populated from Drupal, so it's worth checking it there.
